FROM node:18-alpine as builder
WORKDIR /app
COPY ./FrontEnd .
WORKDIR /app
ARG VITE_API_URL
RUN echo "VITE_API_URL=$VITE_API_URL" > .env
RUN npm install
RUN npm run build

FROM nginx:alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY ./FrontEnd/nginx/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80